using System.Diagnostics.Metrics;

CREATE TABLE "pengguna" ( "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "nama" varchar NOT NULL, "password" varchar NOT NULL);

CREATE TABLE "tugas" ( "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "nama_tugas" varchar NOT NULL );

ALTER TABLE "pengguna" ADD FOREIGN KEY ("id") REFERENCES "tugas" ("id");

select* from pengguna

select * from tugas